#!/usr/bin/env python
# -*- coding: ANSI_X3.4-1968 -*-
# generated by wxGlade 0.3.4 on Wed Sep  1 12:48:31 2004

import wx

class psoframe(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: psoframe.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.window_split = wx.SplitterWindow(self, -1, style=wx.SP_3D|wx.SP_BORDER|wx.SP_LIVE_UPDATE)
        self.window_view = wx.Panel(self.window_split, -1)
        self.window_ctrl = wx.Panel(self.window_split, -1)
        self.notebook_ctrl = wx.Notebook(self.window_ctrl, -1, style=0)
        self.notebook_ctrl_pane_sociometry = wx.Panel(self.notebook_ctrl, -1)
        self.notebook_ctrl_pane_motion = wx.ScrolledWindow(self.notebook_ctrl, -1, style=wx.TAB_TRAVERSAL)
        self.notebook_ctrl_pane_function = wx.Panel(self.notebook_ctrl, -1)
        self.panel_global = wx.Panel(self.window_ctrl, -1, style=wx.DOUBLE_BORDER|wx.RAISED_BORDER|wx.TAB_TRAVERSAL)
        self.sizer_function_staticbox = wx.StaticBox(self.notebook_ctrl_pane_function, -1, "")
        self.sizer_motion_staticbox = wx.StaticBox(self.notebook_ctrl_pane_motion, -1, "")
        self.sizer_sociometry_staticbox = wx.StaticBox(self.notebook_ctrl_pane_sociometry, -1, "")
        self.panel_start = wx.Panel(self.window_ctrl, -1, style=wx.DOUBLE_BORDER|wx.RAISED_BORDER|wx.STATIC_BORDER)
        
        # Menu Bar
        self.PSO_menubar = wx.MenuBar()
        self.SetMenuBar(self.PSO_menubar)
        self.file = wx.Menu()
        self.exit = wx.MenuItem(self.file, wx.NewId(), "E&xit", "", wx.ITEM_NORMAL)
        self.file.AppendItem(self.exit)
        self.PSO_menubar.Append(self.file, "&File")
        self.help = wx.Menu()
        self.about = wx.MenuItem(self.help, wx.NewId(), "&About", "", wx.ITEM_NORMAL)
        self.help.AppendItem(self.about)
        self.PSO_menubar.Append(self.help, "&Help")
        # Menu Bar end
        self.statusbar = self.CreateStatusBar(2, wx.ST_SIZEGRIP)
        self.label_choices = wx.StaticText(self.panel_start, -1, "label_choices", style=wx.ALIGN_CENTRE|wx.ST_NO_AUTORESIZE)
        self.button_start = wx.Button(self.panel_start, -1, "Start")
        self.label_numparts = wx.StaticText(self.panel_global, -1, "Particles:", style=wx.ALIGN_RIGHT)
        self.slider_numparts = wx.Slider(self.panel_global, -1, 5, 2, 100, style=wx.SL_HORIZONTAL|wx.SL_AUTOTICKS|wx.SL_LABELS|wx.SL_TOP)
        self.label_dimensions = wx.StaticText(self.panel_global, -1, "Dimensions:")
        self.slider_dimensions = wx.Slider(self.panel_global, -1, 2, 1, 100, style=wx.SL_HORIZONTAL|wx.SL_AUTOTICKS|wx.SL_LABELS|wx.SL_TOP)
        self.panel_ctrl_simulation = wx.ScrolledWindow(self.window_ctrl, -1, style=wx.DOUBLE_BORDER|wx.RAISED_BORDER|wx.TAB_TRAVERSAL)
        self.choice_function = wx.Choice(self.notebook_ctrl_pane_function, -1, choices=[])
        self.panel_ctrl_function = wx.ScrolledWindow(self.notebook_ctrl_pane_function, -1, style=wx.DOUBLE_BORDER|wx.RAISED_BORDER|wx.TAB_TRAVERSAL)
        self.choice_motion = wx.Choice(self.notebook_ctrl_pane_motion, -1, choices=[])
        self.panel_ctrl_motion = wx.ScrolledWindow(self.notebook_ctrl_pane_motion, -1, style=wx.DOUBLE_BORDER|wx.RAISED_BORDER|wx.TAB_TRAVERSAL)
        self.choice_sociometry = wx.Choice(self.notebook_ctrl_pane_sociometry, -1, choices=[])
        self.panel_ctrl_sociometry = wx.Panel(self.notebook_ctrl_pane_sociometry, -1, style=wx.DOUBLE_BORDER|wx.RAISED_BORDER)
        self.panel_view = wx.Panel(self.window_view, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: psoframe.__set_properties
        self.SetTitle("PSO")
        self.SetSize((800, 600))
        self.statusbar.SetStatusWidths([-2, -3])
        # statusbar fields
        statusbar_fields = ["", ""]
        for i in range(len(statusbar_fields)):
            self.statusbar.SetStatusText(statusbar_fields[i], i)
        self.label_choices.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_numparts.SetToolTipString("Number of particles")
        self.label_dimensions.SetToolTipString("Number of dimensions (only two are shown)")
        self.panel_ctrl_simulation.SetScrollRate(10, 10)
        self.choice_function.SetSelection(0)
        self.panel_ctrl_function.SetScrollRate(10, 10)
        self.choice_motion.SetSelection(0)
        self.panel_ctrl_motion.SetScrollRate(10, 10)
        self.notebook_ctrl_pane_motion.SetScrollRate(10, 10)
        self.choice_sociometry.SetSelection(0)
        self.panel_view.SetBackgroundColour(wx.Colour(0, 0, 0))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: psoframe.__do_layout
        sizer_frame = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_ctrl = wx.BoxSizer(wx.VERTICAL)
        sizer_sociometry = wx.StaticBoxSizer(self.sizer_sociometry_staticbox, wx.VERTICAL)
        sizer_motion = wx.StaticBoxSizer(self.sizer_motion_staticbox, wx.VERTICAL)
        sizer_function = wx.StaticBoxSizer(self.sizer_function_staticbox, wx.VERTICAL)
        grid_sizer_global = wx.FlexGridSizer(3, 2, 2, 2)
        sizer_start = wx.BoxSizer(wx.VERTICAL)
        sizer_start.Add(self.label_choices, 1, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        sizer_start.Add(self.button_start, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ADJUST_MINSIZE, 0)
        self.panel_start.SetAutoLayout(True)
        self.panel_start.SetSizer(sizer_start)
        sizer_start.Fit(self.panel_start)
        sizer_start.SetSizeHints(self.panel_start)
        sizer_ctrl.Add(self.panel_start, 0, wx.ALL|wx.EXPAND, 2)
        grid_sizer_global.Add(self.label_numparts, 0, 0, 0)
        grid_sizer_global.Add(self.slider_numparts, 0, wx.EXPAND, 0)
        grid_sizer_global.Add(self.label_dimensions, 0, 0, 0)
        grid_sizer_global.Add(self.slider_dimensions, 0, wx.EXPAND, 0)
        self.panel_global.SetAutoLayout(True)
        self.panel_global.SetSizer(grid_sizer_global)
        grid_sizer_global.Fit(self.panel_global)
        grid_sizer_global.SetSizeHints(self.panel_global)
        grid_sizer_global.AddGrowableRow(0)
        grid_sizer_global.AddGrowableRow(1)
        grid_sizer_global.AddGrowableCol(1)
        sizer_ctrl.Add(self.panel_global, 0, wx.ALL|wx.EXPAND, 2)
        sizer_ctrl.Add(self.panel_ctrl_simulation, 1, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 2)
        sizer_function.Add(self.choice_function, 0, wx.EXPAND, 0)
        sizer_function.Add(self.panel_ctrl_function, 1, wx.EXPAND, 0)
        self.notebook_ctrl_pane_function.SetAutoLayout(True)
        self.notebook_ctrl_pane_function.SetSizer(sizer_function)
        sizer_function.Fit(self.notebook_ctrl_pane_function)
        sizer_function.SetSizeHints(self.notebook_ctrl_pane_function)
        sizer_motion.Add(self.choice_motion, 0, wx.EXPAND, 0)
        sizer_motion.Add(self.panel_ctrl_motion, 1, wx.EXPAND, 0)
        self.notebook_ctrl_pane_motion.SetAutoLayout(True)
        self.notebook_ctrl_pane_motion.SetSizer(sizer_motion)
        sizer_motion.Fit(self.notebook_ctrl_pane_motion)
        sizer_motion.SetSizeHints(self.notebook_ctrl_pane_motion)
        sizer_sociometry.Add(self.choice_sociometry, 0, wx.EXPAND, 0)
        sizer_sociometry.Add(self.panel_ctrl_sociometry, 1, wx.EXPAND, 0)
        self.notebook_ctrl_pane_sociometry.SetAutoLayout(True)
        self.notebook_ctrl_pane_sociometry.SetSizer(sizer_sociometry)
        sizer_sociometry.Fit(self.notebook_ctrl_pane_sociometry)
        sizer_sociometry.SetSizeHints(self.notebook_ctrl_pane_sociometry)
        self.notebook_ctrl.AddPage(self.notebook_ctrl_pane_function, "Function")
        self.notebook_ctrl.AddPage(self.notebook_ctrl_pane_motion, "Motion")
        self.notebook_ctrl.AddPage(self.notebook_ctrl_pane_sociometry, "Sociometry")
        sizer_ctrl.Add(wx.NotebookSizer(self.notebook_ctrl), 2, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 2)
        self.window_ctrl.SetAutoLayout(True)
        self.window_ctrl.SetSizer(sizer_ctrl)
        sizer_ctrl.Fit(self.window_ctrl)
        sizer_ctrl.SetSizeHints(self.window_ctrl)
        sizer_6.Add(self.panel_view, 1, wx.EXPAND, 0)
        self.window_view.SetAutoLayout(True)
        self.window_view.SetSizer(sizer_6)
        sizer_6.Fit(self.window_view)
        sizer_6.SetSizeHints(self.window_view)
        self.window_split.SplitVertically(self.window_ctrl, self.window_view, 249)
        sizer_frame.Add(self.window_split, 1, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_frame)
        self.Layout()
        # end wxGlade

# end of class psoframe


